version: '3'

services:

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/database

# webpacker:

# postgres

  database:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env/development/database

volumes:
  db_data:
